/*
 * Generated by XDoclet - Do not edit!
 */
package com.hex.amaze.application.petstore.entity.interfaces;

/**
 * Data object for Book.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public class BookData
   extends java.lang.Object
   implements java.io.Serializable
{
   private java.lang.Integer id;
   private java.lang.String title;
   private java.lang.String author;
   private java.lang.Boolean available;
   private java.lang.Integer userId;

  /* begin value object */
   private BookValue BookValue = null;

   public BookValue getBookValue()
   {
	  if( BookValue == null )
	  {
          BookValue = new BookValue();
	  }
      try
         {
            BookValue.setId( getId() );
            BookValue.setTitle( getTitle() );
            BookValue.setAuthor( getAuthor() );
            BookValue.setAvailable( getAvailable() );
            BookValue.setUserId( getUserId() );
                   }
         catch (Exception e)
         {
            throw new javax.ejb.EJBException(e);
         }

	  return BookValue;
   }

   public void setBookValue( BookValue valueHolder )
   {

	  try
	  {
		 setTitle( valueHolder.getTitle() );
		 setAuthor( valueHolder.getAuthor() );
		 setAvailable( valueHolder.getAvailable() );
		 setUserId( valueHolder.getUserId() );
	  }
	  catch (Exception e)
	  {
		 throw new javax.ejb.EJBException(e);
	  }
   }

  /* end value object */

   public BookData()
   {
   }

   public BookData( java.lang.Integer id,java.lang.String title,java.lang.String author,java.lang.Boolean available,java.lang.Integer userId )
   {
      setId(id);
      setTitle(title);
      setAuthor(author);
      setAvailable(available);
      setUserId(userId);
   }

   public BookData( BookData otherData )
   {
      setId(otherData.getId());
      setTitle(otherData.getTitle());
      setAuthor(otherData.getAuthor());
      setAvailable(otherData.getAvailable());
      setUserId(otherData.getUserId());

   }

   public java.lang.Integer getPrimaryKey() {
     return  getId();
   }

   public java.lang.Integer getId()
   {
      return this.id;
   }
   public void setId( java.lang.Integer id )
   {
      this.id = id;
   }

   public java.lang.String getTitle()
   {
      return this.title;
   }
   public void setTitle( java.lang.String title )
   {
      this.title = title;
   }

   public java.lang.String getAuthor()
   {
      return this.author;
   }
   public void setAuthor( java.lang.String author )
   {
      this.author = author;
   }

   public java.lang.Boolean getAvailable()
   {
      return this.available;
   }
   public void setAvailable( java.lang.Boolean available )
   {
      this.available = available;
   }

   public java.lang.Integer getUserId()
   {
      return this.userId;
   }
   public void setUserId( java.lang.Integer userId )
   {
      this.userId = userId;
   }

   public String toString()
   {
      StringBuffer str = new StringBuffer("{");

      str.append("id=" + getId() + " " + "title=" + getTitle() + " " + "author=" + getAuthor() + " " + "available=" + getAvailable() + " " + "userId=" + getUserId());
      str.append('}');

      return(str.toString());
   }

   public boolean equals( Object pOther )
   {
      if( pOther instanceof BookData )
      {
         BookData lTest = (BookData) pOther;
         boolean lEquals = true;

         if( this.id == null )
         {
            lEquals = lEquals && ( lTest.id == null );
         }
         else
         {
            lEquals = lEquals && this.id.equals( lTest.id );
         }
         if( this.title == null )
         {
            lEquals = lEquals && ( lTest.title == null );
         }
         else
         {
            lEquals = lEquals && this.title.equals( lTest.title );
         }
         if( this.author == null )
         {
            lEquals = lEquals && ( lTest.author == null );
         }
         else
         {
            lEquals = lEquals && this.author.equals( lTest.author );
         }
         if( this.available == null )
         {
            lEquals = lEquals && ( lTest.available == null );
         }
         else
         {
            lEquals = lEquals && this.available.equals( lTest.available );
         }
         if( this.userId == null )
         {
            lEquals = lEquals && ( lTest.userId == null );
         }
         else
         {
            lEquals = lEquals && this.userId.equals( lTest.userId );
         }

         return lEquals;
      }
      else
      {
         return false;
      }
   }

   public int hashCode()
   {
      int result = 17;

      result = 37*result + ((this.id != null) ? this.id.hashCode() : 0);

      result = 37*result + ((this.title != null) ? this.title.hashCode() : 0);

      result = 37*result + ((this.author != null) ? this.author.hashCode() : 0);

      result = 37*result + ((this.available != null) ? this.available.hashCode() : 0);

      result = 37*result + ((this.userId != null) ? this.userId.hashCode() : 0);

      return result;
   }

}
