/*
 * Generated by XDoclet - Do not edit!
 */
package com.hex.amaze.application.petstore.entity.interfaces;

/**
 * Local interface for Book.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface BookLocal
   extends javax.ejb.EJBLocalObject
{

   public java.lang.Integer getId(  ) ;

   public void setId( java.lang.Integer id ) ;

   public java.lang.String getTitle(  ) ;

   public void setTitle( java.lang.String title ) ;

   public java.lang.String getAuthor(  ) ;

   public void setAuthor( java.lang.String author ) ;

   public java.lang.Boolean getAvailable(  ) ;

   public void setAvailable( java.lang.Boolean available ) ;

   public java.lang.Integer getUserId(  ) ;

   public void setUserId( java.lang.Integer user_id ) ;

   public UserLocal getUser(  ) ;

   public void setUser( UserLocal user ) ;

   public BookValue getBookValue(  ) ;

   public void setBookValue( BookValue bookValue ) ;

}
