/*
 * Generated by XDoclet - Do not edit!
 */
package com.hex.amaze.application.petstore.entity.interfaces;

/**
 * Remote interface for Book.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface Book
   extends javax.ejb.EJBObject
{

   public java.lang.Integer getId(  )
      throws java.rmi.RemoteException;

   public void setId( java.lang.Integer id )
      throws java.rmi.RemoteException;

   public java.lang.String getTitle(  )
      throws java.rmi.RemoteException;

   public void setTitle( java.lang.String title )
      throws java.rmi.RemoteException;

   public java.lang.String getAuthor(  )
      throws java.rmi.RemoteException;

   public void setAuthor( java.lang.String author )
      throws java.rmi.RemoteException;

   public java.lang.Boolean getAvailable(  )
      throws java.rmi.RemoteException;

   public void setAvailable( java.lang.Boolean available )
      throws java.rmi.RemoteException;

   public java.lang.Integer getUserId(  )
      throws java.rmi.RemoteException;

   public void setUserId( java.lang.Integer user_id )
      throws java.rmi.RemoteException;

   public BookValue getBookValue(  )
      throws java.rmi.RemoteException;

   public void setBookValue( BookValue bookValue )
      throws java.rmi.RemoteException;

}
