/*
 * Generated by XDoclet - Do not edit!
 */
package com.hex.amaze.application.petstore.entity.interfaces;

/**
 * Local interface for User.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface UserLocal
   extends javax.ejb.EJBLocalObject
{

   public java.lang.Integer getId(  ) ;

   public void setId( java.lang.Integer id ) ;

   public java.lang.String getName(  ) ;

   public void setName( java.lang.String name ) ;

   public java.lang.String getLastName(  ) ;

   public void setLastName( java.lang.String lastname ) ;

   public java.lang.Integer getAge(  ) ;

   public void setAge( java.lang.Integer age ) ;

   public java.util.Collection getBooks(  ) ;

   public void setBooks( java.util.Collection books ) ;

   public UserValue getUserValue(  ) ;

   public void setUserValue(UserValue userValue ) ;

}
