/*
 * Generated by XDoclet - Do not edit!
 */
package com.hex.amaze.application.petstore.entity.interfaces;

/**
 * Local home interface for User.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface UserLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/UserLocal";
   public static final String JNDI_NAME="ejb/UserLocalHome";

   public UserLocal create()
      throws javax.ejb.CreateException;

   public java.util.Collection findAll()
      throws javax.ejb.FinderException;

   public UserLocal findByPrimaryKey(java.lang.Integer pk)
      throws javax.ejb.FinderException;

}
