/*
 * Generated by XDoclet - Do not edit!
 */
package com.hex.amaze.application.petstore.entity.interfaces;

/**
 * Data object for User.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public class UserData
   extends java.lang.Object
   implements java.io.Serializable
{
   private java.lang.Integer id;
   private java.lang.String name;
   private java.lang.String lastName;
   private java.lang.Integer age;

  /* begin value object */
   private UserValue UserValue = null;

   public UserValue getUserValue()
   {
	  if( UserValue == null )
	  {
          UserValue = new UserValue();
	  }
      try
         {
            UserValue.setId( getId() );
            UserValue.setName( getName() );
            UserValue.setLastName( getLastName() );
            UserValue.setAge( getAge() );
                   }
         catch (Exception e)
         {
            throw new javax.ejb.EJBException(e);
         }

	  return UserValue;
   }

   public void setUserValue( UserValue valueHolder )
   {

	  try
	  {
		 setName( valueHolder.getName() );
		 setLastName( valueHolder.getLastName() );
		 setAge( valueHolder.getAge() );
	  }
	  catch (Exception e)
	  {
		 throw new javax.ejb.EJBException(e);
	  }
   }

  /* end value object */

   public UserData()
   {
   }

   public UserData( java.lang.Integer id,java.lang.String name,java.lang.String lastName,java.lang.Integer age )
   {
      setId(id);
      setName(name);
      setLastName(lastName);
      setAge(age);
   }

   public UserData( UserData otherData )
   {
      setId(otherData.getId());
      setName(otherData.getName());
      setLastName(otherData.getLastName());
      setAge(otherData.getAge());

   }

   public java.lang.Integer getPrimaryKey() {
     return  getId();
   }

   public java.lang.Integer getId()
   {
      return this.id;
   }
   public void setId( java.lang.Integer id )
   {
      this.id = id;
   }

   public java.lang.String getName()
   {
      return this.name;
   }
   public void setName( java.lang.String name )
   {
      this.name = name;
   }

   public java.lang.String getLastName()
   {
      return this.lastName;
   }
   public void setLastName( java.lang.String lastName )
   {
      this.lastName = lastName;
   }

   public java.lang.Integer getAge()
   {
      return this.age;
   }
   public void setAge( java.lang.Integer age )
   {
      this.age = age;
   }

   public String toString()
   {
      StringBuffer str = new StringBuffer("{");

      str.append("id=" + getId() + " " + "name=" + getName() + " " + "lastName=" + getLastName() + " " + "age=" + getAge());
      str.append('}');

      return(str.toString());
   }

   public boolean equals( Object pOther )
   {
      if( pOther instanceof UserData )
      {
         UserData lTest = (UserData) pOther;
         boolean lEquals = true;

         if( this.id == null )
         {
            lEquals = lEquals && ( lTest.id == null );
         }
         else
         {
            lEquals = lEquals && this.id.equals( lTest.id );
         }
         if( this.name == null )
         {
            lEquals = lEquals && ( lTest.name == null );
         }
         else
         {
            lEquals = lEquals && this.name.equals( lTest.name );
         }
         if( this.lastName == null )
         {
            lEquals = lEquals && ( lTest.lastName == null );
         }
         else
         {
            lEquals = lEquals && this.lastName.equals( lTest.lastName );
         }
         if( this.age == null )
         {
            lEquals = lEquals && ( lTest.age == null );
         }
         else
         {
            lEquals = lEquals && this.age.equals( lTest.age );
         }

         return lEquals;
      }
      else
      {
         return false;
      }
   }

   public int hashCode()
   {
      int result = 17;

      result = 37*result + ((this.id != null) ? this.id.hashCode() : 0);

      result = 37*result + ((this.name != null) ? this.name.hashCode() : 0);

      result = 37*result + ((this.lastName != null) ? this.lastName.hashCode() : 0);

      result = 37*result + ((this.age != null) ? this.age.hashCode() : 0);

      return result;
   }

}
