/*
 * Generated by XDoclet - Do not edit!
 */
package com.hex.amaze.application.petstore.entity.interfaces;

/**
 * Remote interface for User.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface User
   extends javax.ejb.EJBObject
{

   public java.lang.Integer getId(  )
      throws java.rmi.RemoteException;

   public void setId( java.lang.Integer id )
      throws java.rmi.RemoteException;

   public java.lang.String getName(  )
      throws java.rmi.RemoteException;

   public void setName( java.lang.String name )
      throws java.rmi.RemoteException;

   public java.lang.String getLastName(  )
      throws java.rmi.RemoteException;

   public void setLastName( java.lang.String lastname )
      throws java.rmi.RemoteException;

   public java.lang.Integer getAge(  )
      throws java.rmi.RemoteException;

   public void setAge( java.lang.Integer age )
      throws java.rmi.RemoteException;

   public UserValue getUserValue(  )
      throws java.rmi.RemoteException;

   public void setUserValue( UserValue userValue )
      throws java.rmi.RemoteException;

}
