/*
 * Generated by XDoclet - Do not edit!
 */
package com.hex.amaze.application.petstore.session.interfaces;

/**
 * Home interface for BookSession.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface BookSessionHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/BookSession";
   public static final String JNDI_NAME="BookSession";

   public BookSession create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
