/*
 * Generated by XDoclet - Do not edit!
 */
package com.hex.amaze.application.petstore.session.interfaces;

/**
 * Local home interface for BookSession.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface BookSessionLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/BookSessionLocal";
   public static final String JNDI_NAME="BookSessionLocal";

   public BookSessionLocal create()
      throws javax.ejb.CreateException;

}
