
  CREATE OR REPLACE NONEDITIONABLE TYPE ORA_MIGRA.SOLID_TYP AS OBJECT (
  len    INTEGER,
  wth    INTEGER,
  hgt    INTEGER,
  MEMBER FUNCTION volume RETURN INTEGER );
/

CREATE OR REPLACE NONEDITIONABLE TYPE BODY ORA_MIGRA.SOLID_TYP AS
  MEMBER FUNCTION volume RETURN INTEGER IS
  BEGIN
    RETURN len * wth * hgt;
  END;
END;
/

  CREATE OR REPLACE NONEDITIONABLE TYPE ORA_MIGRA.FULL_MAILING_ADDRESS_TYPE AS OBJECT
( Street       VARCHAR2(80),
  City         VARCHAR2(80),
  State        CHAR(2),
  Zip          VARCHAR2(10) );
/

  CREATE OR REPLACE NONEDITIONABLE TYPE ORA_MIGRA.STACK AS OBJECT ( 
   max_size INTEGER, 
   top      INTEGER,   
   MEMBER PROCEDURE initialize,
   MEMBER FUNCTION full RETURN BOOLEAN,
   MEMBER FUNCTION empty RETURN BOOLEAN,
   MEMBER PROCEDURE push (n IN INTEGER),
   MEMBER PROCEDURE pop (n OUT INTEGER)
);
/

