
   CREATE SEQUENCE  ORA_MIGRA.EMPLOYEES_SEQ  
   MINVALUE 1 
   MAXVALUE 9999999999999999999999999999 
   INCREMENT BY 1 
   START WITH 1 
   NOCACHE  
   NOORDER  
   NOCYCLE  
   NOKEEP  
   NOSCALE  
   GLOBAL ;

   CREATE SEQUENCE  ORA_MIGRA.LOCATIONS_SEQ  
   MINVALUE 1 
   MAXVALUE 9900 
   INCREMENT BY 100 
   START WITH 1 
   NOCACHE  
   NOORDER  
   NOCYCLE  
   NOKEEP  
   NOSCALE  
   GLOBAL ;

   CREATE SEQUENCE  ORA_MIGRA.SAMPLE_SEQ  
   MINVALUE 1 
   MAXVALUE 9999999999999999999999999999 
   INCREMENT BY 1 
   START WITH 1 
   CACHE 20 
   NOORDER  
   NOCYCLE  
   NOKEEP  
   NOSCALE  
   GLOBAL ;

   CREATE SEQUENCE  ORA_MIGRA.DEPARTMENTS_SEQ  
   MINVALUE 1 
   MAXVALUE 9990 
   INCREMENT BY 10 
   START WITH 1 
   NOCACHE  
   NOORDER  
   NOCYCLE  
   NOKEEP  
   NOSCALE  
   GLOBAL ;

   CREATE SEQUENCE  ORA_MIGRA.SEQQ1  
   MINVALUE 1 
   MAXVALUE 9999999999999999999999999999 
   INCREMENT BY 1 
   START WITH 1 
   CACHE 20 
   NOORDER  
   NOCYCLE  
   NOKEEP  
   NOSCALE  
   GLOBAL ;
   
   /*

DROP SEQUENCE ORA_MIGRA.DEPARTMENTS_SEQ ;
DROP SEQUENCE ORA_MIGRA.EMPLOYEES_SEQ ;
DROP SEQUENCE ORA_MIGRA.LOCATIONS_SEQ ;
DROP SEQUENCE ORA_MIGRA.SAMPLE_SEQ ;
DROP SEQUENCE ORA_MIGRA.SEQQ1 ;
*/
