
  CREATE OR REPLACE FORCE NONEDITIONABLE VIEW ORA_MIGRA.EMP_VIEW (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) AS 
  select EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID from ORA_MIGRA.EMPLOYEES
  ;

  CREATE OR REPLACE FORCE EDITIONABLE VIEW ORA_MIGRA.MITARBEITER (ID, THOMAEMA, INAKTIV, ANREDE, TITEL, VORNAME, VORSATZWORT, NACHNAME, KUERZEL, USERNAME, ORGEINHEITID, ERSTTELEFON, KOSTENSTELLE, ETAGE, GEBAEUDE, EXT_TELEFON, MAIL_ADRESSE, USI_KUERZEL, USERNAME_ALT, HAUSPOSTZAHL, RAUMID, SEKTOR, RAUM_HAUPT_NR, RAUM_UNTER_NR, FAX, TECHNISCHER_USER, BETR_MITARBEITER_ID, SMTP_ADRESSE, DC, STANDORTID, IMPORT_JN, MITARBEITER_BI_ID, USERNAME_IMPORT, DELDAT, SLAVE_ACCOUNT, MENSCH_JN, AUSWEISNUMMER, MITARB_BI_ID_POT_TEMP, KEIN_ARBEITSPLATZ_PAMI, KEIN_ARBEITSPLATZ_SAP, KEIN_ARBEITSPLATZ, EXTERNE_FIRMA, MOBILTELEFON, AD_ACCOUNT_AKTIV, DEFAULT_MAILADRESSE, ISMANAGER_JN, MITARBEITER_BI_ID_SAVE, AKTIV_JN_BI, AUSWEIS_ABLAUFDATUM, AUSTRITTSDATUM_SOLL, IMMER_IN_MARB_VIEW_JN, PERSONALNUMMER, VERTRAUENS_ARB_ZEIT_JN, ORG_EINHEIT_AUS_MAIL) AS 
  SELECT m.ID, m.THOMAEMA, m.INAKTIV, m.ANREDE, m.TITEL, m.VORNAME,
  m.VORSATZWORT, m.NACHNAME,
  m.KUERZEL, m.USERNAME, m.ORGEINHEITID,
  m.ERSTTELEFON, m.KOSTENSTELLE, m.ETAGE,
  m.GEBAEUDE, m.EXT_TELEFON,
  m.MAIL_ADRESSE, m.USI_KUERZEL, m.USERNAME_ALT, m.HAUSPOSTZAHL, m.RAUMID,
  m.SEKTOR, m.RAUM_HAUPT_NR, m.RAUM_UNTER_NR, m.FAX, m.TECHNISCHER_USER,
  m.BETR_MITARBEITER_ID, m.SMTP_ADRESSE, m.DC, m.STANDORTID, m.IMPORT_JN,
  m.MITARBEITER_BI_ID, m.USERNAME_IMPORT, m.DELDAT, m.SLAVE_ACCOUNT,
  m.MENSCH_JN, m.AUSWEISNUMMER, m.MITARB_BI_ID_POT_TEMP, m.KEIN_ARBEITSPLATZ_PAMI,
  m.KEIN_ARBEITSPLATZ_SAP, m.KEIN_ARBEITSPLATZ, m.EXTERNE_FIRMA, m.MOBILTELEFON,
  m.AD_ACCOUNT_AKTIV, m.DEFAULT_MAILADRESSE, m.ISMANAGER_JN, m.MITARBEITER_BI_ID_SAVE,
  m.AKTIV_JN_BI, m.AUSWEIS_ABLAUFDATUM, m.AUSTRITTSDATUM_SOLL, m.IMMER_IN_MARB_VIEW_JN,
  m.PERSONALNUMMER, m.Vertrauens_Arb_Zeit_JN,
  m.Org_Einheit_aus_Mail
    from ORA_MIGRA.MITARBEITER_bi_alle m where
          m.standortid in (1,2,23,44,63,107,780,292)
          or m.standortid is null
          or m.IMMER_IN_MARB_VIEW_JN = 'J'
          or exists (select mh2.mitarbeiter_id from ORA_MIGRA.Mitarbeiter_Standort_Hist mh2 where
                        mh2.mitarbeiter_id = m.id
                        and (mh2.STANDORT_ID_Old is null or mh2.STANDORT_ID_Old in (1,2,23,44,63,107))
                     )
;					 
	
  CREATE OR REPLACE FORCE EDITIONABLE VIEW ORA_MIGRA.ETAGE_V (ID, GEBAEUDEID, DC, UC, ETAGE, LOCKED, DM, UM, TRAG, VERKEHR, SCHALL, DELDAT, PROJEKTID, SORTIERFOLGE) AS 
  SELECT e.ID, e.GEBAEUDEID, e.DC, e.UC, e.ETAGE, e.LOCKED, e.DM, e.UM, e.TRAG, e.VERKEHR,
        e.SCHALL, e.DELDAT, e.PROJEKTID,ETAGENSORTIERFOLGE(e.ETAGE) as SORTIERFOLGE
FROM ORA_MIGRA.ETAGE e
;

  CREATE OR REPLACE FORCE EDITIONABLE VIEW ORA_MIGRA.ETAGE_GEB_STD_V (STANDORT_ID, STANDORT, GEBAEUDE_ID, GEBAEUDE, BEZEICHNUNG, ETAGE_ID, ETAGE, SEKTOR, SAP_WELT_ID, SORTIERFOLGE) AS 
  SELECT
  S.ID STANDORT_ID
  , S.STANDORT
  , G.ID GEBAEUDE_ID
  , G.GEBAEUDE || G.SEKTOR GEBAEUDE
  , G.BEZEICHNUNG
  , E.ID ETAGE_ID
  , E.ETAGE
  , G.SEKTOR
  , S.SAP_WELT_ID
  , E.SORTIERFOLGE
FROM ORA_MIGRA.ETAGE_V E,ORA_MIGRA.GEBAEUDE G, ORA_MIGRA.STANDORT S
WHERE E.GEBAEUDEID = G.ID
AND S.ID = G.STANDORTID
;

  CREATE OR REPLACE FORCE EDITIONABLE VIEW ORA_MIGRA.CRESTRON_FUSION_RAUM (STANDORT_ID, VR_RAUM_NAME, VR_AKTIV, RAUM_NR_GES_GEB, RAUM_NR_PUNKT, RAUM_VERRAUM_BEZ, RAUM_BEZ, VERANST_RAUM_ID, RAUM_ID) AS 
  SELECT
  S.ID AS STANDORT_ID,
  VR.VR_RAUM_NAME,
  VR.VR_AKTIV,
  G.GEBAEUDE || '_' || E.ETAGE  || '_' || R.SEKTOR || R.RAUM || '_' || R.UNTER AS RAUM_NR_GES_GEB,
  G.GEBAEUDE || R.SEKTOR || '.' || E.ETAGE  || '.' ||  R.RAUM || '.' || R.UNTER AS RAUM_NR_PUNKT,
  PCK_CRESTRONFUSION_EXPORT.GET_RAUM_VERRAUM_BEZ(RIR.RAUM_ID) AS RAUM_VERRAUM_BEZ,
  R.BEZEICHNUNG AS RAUM_BEZ,
  VR.VR_ID AS VERANST_RAUM_ID,
  RIR.RAUM_ID AS RAUM_ID
  FROM (SELECT  VR.BEZEICHNUNG1 AS VR_RAUM_NAME,  VR.ID AS VR_ID, VR.AKTIV  AS VR_AKTIV
        FROM ORA_MIGRA.VERANST_RAUM VR, ORA_MIGRA.RAUM_TYP RT
        WHERE VR.RAUM_TYP_ID = RT.ID
        AND RT.BEZEICHNUNG <> 'BÜRO'
        AND VR.DELDAT IS NULL
        AND VR.AKTIV = 'J') VR, ORA_MIGRA.RAUM_IN_VERANST_RAUM RIR,
    ORA_MIGRA.STANDORT S, ORA_MIGRA.GEBAEUDE G, ORA_MIGRA.ETAGE E, ORA_MIGRA.RAUM R WHERE
     VR.VR_ID = RIR.VERANST_RAUM_ID
     AND RIR.RAUM_ID = R.ID
     AND R.ETAGEID = E.ID
     AND E.GEBAEUDEID = G.ID
     AND G.STANDORTID = S.ID
      AND S.ID IN (SELECT WS.STANDORT_ID FROM ORA_MIGRA.WEB_STANDORT WS WHERE WS.SICHTBAR_IM_WEB = 'J')
    -- AND S.ID IN (1, 2, 23, 63, 245) -- NUR BIBERACHER, INGELHEIMER, DORTMUNDER, WIENER UND MAINZER
;

  CREATE OR REPLACE FORCE EDITIONABLE VIEW ORA_MIGRA.CRESTRON_FUSION_EXP_FILE (RAUM_ID, BEGINN_TERMIN_DATE, BEGINN_PUFFER_DATE, BEGINN_PUFFER_DATUM_CHAR, BEGINN_PUFFER_ZEIT_NORM, ENDE_TERMIN_DATE, ENDE_TERMIN_DATUM_CHAR, ENDE_TERMIN_ZEIT_NORM, THEMA_NORM, MITARBEITER_ID, BETREUER, VR_RAUM_NAME, VERANSTALTUNG_STATUS) AS 
  select  CRESTRON_FUSION_RAUM.RAUM_ID,
        veranst.beginn_termin as beginn_termin_Date,
        veranst.BEGINN_PUFFER as beginn_puffer_date,
        to_char(veranst.BEGINN_PUFFER,'mm/dd/yyyy') as BEGINN_PUFFER_Datum_Char,
        to_char(trunc(veranst.BEGINN_PUFFER) +  (trunc((veranst.BEGINN_PUFFER - trunc(veranst.BEGINN_PUFFER)) * 24 * 2 ))/(24 * 2),'HH24:MI:SS') as beginn_PUFFER_Zeit_norm,
        veranst.ENDE_TERMIN as ende_termin_date,
        to_char(veranst.ENDE_TERMIN,'mm/dd/yyyy') as ENDE_TERMIN_Datum_Char,
        to_char(PCK_CrestronFusion_EXPORT.round_up_half_hour(veranst.ENDE_TERMIN),'HH24:MI:SS') as ENDE_TERMIN_Zeit_norm,
        replace(replace(replace(replace(veranst.THEMA,chr(09),''),chr(10),''),chr(13),''),';',' ') as thema_norm,
        veranst.MITARBEITER_ID,
        veranst.BETREUER,
        CRESTRON_FUSION_RAUM.VR_RAUM_NAME,
        veranst.Veranstaltung_Status
        from (select b.BEGINN_PUFFER, b.BEGINN_TERMIN, b.ENDE_TERMIN, V.THEMA,
              v.MITARBEITER_ID, BETREUER, b.VERANST_RAUM_ID, V.STATUS as Veranstaltung_Status
              from ORA_MIGRA.BESTELLUNG b, ORA_MIGRA.VERANSTALTUNG v where
              b.VERANSTALTUNG_ID = v.id
              and b.dienst_typ = 'R' -- Veranst-Raum
              and V.STATUS IN ('E','B')
              and b.BESTAET_STATUS <> 'S'
              and b.ENDE_TERMIN >= trunc(sysdate) - 21) veranst, CRESTRON_FUSION_RAUM
        where CRESTRON_FUSION_RAUM.VERANST_RAUM_ID = veranst.VERANST_RAUM_ID
;

/*

DROP VIEW ORA_MIGRA.EMP_VIEW ;
DROP VIEW ORA_MIGRA.MITARBEITER ;
DROP VIEW ORA_MIGRA.ETAGE_V ;
DROP VIEW ORA_MIGRA.ETAGE_GEB_STD_V ;
DROP VIEW ORA_MIGRA.CRESTRON_FUSION_RAUM ;
DROP VIEW ORA_MIGRA.CRESTRON_FUSION_EXP_FILE ;

*/		
