DROP MATERIALIZED VIEW ORA_MIGRA.EMP_AGGR_MV;
DROP MATERIALIZED VIEW ORA_MIGRA.MV_EMP_DETAILS;
DROP MATERIALIZED VIEW if exists ORA_MIGRA.EMP_AGGR_MV_DUPL cascade;

  CREATE MATERIALIZED VIEW ORA_MIGRA.EMP_AGGR_MV (DEPARTMENT_ID, SAL_BY_DEPT)
  SEGMENT CREATION IMMEDIATE
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS 
  BUILD IMMEDIATE
  USING INDEX 
  REFRESH FORCE ON DEMAND
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE ON QUERY COMPUTATION ENABLE QUERY REWRITE
  AS SELECT department_id, SUM(salary) AS sal_by_dept
FROM   employees
GROUP BY department_id ;

 COMMENT ON MATERIALIZED VIEW ORA_MIGRA.EMP_AGGR_MV  IS 'snapshot table for snapshot ORA_MIGRA.EMP_AGGR_MV';


  CREATE MATERIALIZED VIEW ORA_MIGRA.EMP_AGGR_MV_DUPL (DEPARTMENT_ID, SAL_BY_DEPT)
  SEGMENT CREATION IMMEDIATE
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS 
  BUILD IMMEDIATE
  USING INDEX 
  REFRESH FORCE ON DEMAND
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE ON QUERY COMPUTATION DISABLE QUERY REWRITE
  AS SELECT department_id, SUM(salary) AS sal_by_dept FROM employees GROUP BY department_id ;

/*

DROP INDEX ORA_MIGRA.I_SNAP$_EMP_AGGR_MV;
DROP INDEX ORA_MIGRA.I_SNAP$_EMP_AGGR_MV_DUPL;

  CREATE UNIQUE INDEX ORA_MIGRA.I_SNAP$_EMP_AGGR_MV ON ORA_MIGRA.EMP_AGGR_MV (SYS_OP_MAP_NONNULL(DEPARTMENT_ID)) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS ;


  CREATE UNIQUE INDEX ORA_MIGRA.I_SNAP$_EMP_AGGR_MV_DUPL ON ORA_MIGRA.EMP_AGGR_MV_DUPL (SYS_OP_MAP_NONNULL(DEPARTMENT_ID)) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS ;
*/

   COMMENT ON MATERIALIZED VIEW ORA_MIGRA.EMP_AGGR_MV_DUPL  IS 'snapshot table for snapshot ORA_MIGRA.EMP_AGGR_MV_DUPL';


  CREATE MATERIALIZED VIEW ORA_MIGRA.MV_EMP_DETAILS (EMPLOYEE_ID, EMPLOYEE_NAME, MANAGER_NAME, SALARY, COMMISSION_PCT, DEPARTMENT_NAME, JOB_TITLE, CITY, STATE_PROVINCE, COUNTRY_NAME, REGION_NAME)
  SEGMENT CREATION IMMEDIATE
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS 
  BUILD IMMEDIATE
  USING INDEX 
  REFRESH FORCE ON DEMAND
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE ON QUERY COMPUTATION DISABLE QUERY REWRITE
  AS SELECT
  e.employee_id,
  e.first_name||' '||  e.last_name Employee_name,
  m.first_name||' '|| m.last_name Manager_name,
  e.salary Salary,
  e.commission_pct,
  d.department_name,
  j.job_title,
  l.city,
  l.state_province,
  c.country_name,
  r.region_name
FROM
  employees e,
  employees m,
  departments d,
  jobs j,
  locations l,
  countries c,
  regions r
WHERE e.department_id = d.department_id
  AND e.manager_id = m.employee_id
  AND d.location_id = l.location_id
  AND l.country_id = c.country_id
  AND c.region_id = r.region_id
  AND j.job_id = e.job_id
  ;

   COMMENT ON MATERIALIZED VIEW ORA_MIGRA.MV_EMP_DETAILS  IS 'snapshot table for snapshot ORA_MIGRA.MV_EMP_DETAILS';
