/*
 * Generated by XDoclet - Do not edit!
 */
package com.hex.amaze.application.petstore.entity.ejb;

import com.hex.amaze.application.petstore.entity.interfaces.UserData;
import com.hex.amaze.application.petstore.entity.interfaces.UserValue;

/**
 * CMP layer for User.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public abstract class UserCMP
   extends User
   implements javax.ejb.EntityBean
{

   public UserData getData()
   {
      UserData dataHolder = null;
      try
      {
         dataHolder = new UserData();

         dataHolder.setId( getId() );
         dataHolder.setName( getName() );
         dataHolder.setLastName( getLastName() );
         dataHolder.setAge( getAge() );

      }
      catch (RuntimeException e)
      {
         throw new javax.ejb.EJBException(e);
      }

      return dataHolder;
   }

   public void ejbLoad() throws javax.ejb.EJBException
   {
      super.ejbLoad();
   }

   public void ejbStore() throws javax.ejb.EJBException
   {
         super.ejbStore();
   }

   public void ejbActivate() throws javax.ejb.EJBException
   {
      super.ejbActivate();
   }

   public void ejbPassivate() throws javax.ejb.EJBException
   {
      super.ejbPassivate();

      UserValue = null;
   }

   public void setEntityContext(javax.ejb.EntityContext ctx) throws javax.ejb.EJBException
   {
      super.setEntityContext(ctx);
   }

   public void unsetEntityContext() throws javax.ejb.EJBException
   {
      super.unsetEntityContext();
   }

   public void ejbRemove() throws javax.ejb.EJBException, javax.ejb.RemoveException
   {
      super.ejbRemove();

   }

 /* Value Objects BEGIN */

   private UserValue UserValue = null;

   public UserValue getUserValue()
   {
      UserValue = new UserValue();
      try
         {
            UserValue.setId( getId() );
            UserValue.setName( getName() );
            UserValue.setLastName( getLastName() );
            UserValue.setAge( getAge() );

         }
         catch (Exception e)
         {
            throw new javax.ejb.EJBException(e);
         }

	  return UserValue;
   }

   public void setUserValue( UserValue valueHolder )
   {

	  try
	  {
		 setName( valueHolder.getName() );
		 setLastName( valueHolder.getLastName() );
		 setAge( valueHolder.getAge() );

	  }
	  catch (Exception e)
	  {
		 throw new javax.ejb.EJBException(e);
	  }
   }

/* Value Objects END */

   public abstract java.lang.Integer getId() ;

   public abstract void setId( java.lang.Integer id ) ;

   public abstract java.lang.String getName() ;

   public abstract void setName( java.lang.String name ) ;

   public abstract java.lang.String getLastName() ;

   public abstract void setLastName( java.lang.String lastName ) ;

   public abstract java.lang.Integer getAge() ;

   public abstract void setAge( java.lang.Integer age ) ;

}
