/*
 * Generated by XDoclet - Do not edit!
 */
package com.hex.amaze.application.petstore.session.ejb;

/**
 * Session layer for UserSession.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public class UserSessionSession
   extends UserSession
   implements javax.ejb.SessionBean
{
   public void ejbActivate() throws javax.ejb.EJBException
   {
      super.ejbActivate();
   }

   public void ejbPassivate() throws javax.ejb.EJBException
   {
      super.ejbPassivate();
   }

   public void setSessionContext(javax.ejb.SessionContext ctx) throws javax.ejb.EJBException
   {
      super.setSessionContext(ctx);
   }

   public void unsetSessionContext() 
   {
   }

   public void ejbRemove() throws javax.ejb.EJBException
   {
      super.ejbRemove();
   }

}
